### ISSUE TITLE
Getting Error, This video is private. If the owner of this video has granted you access

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [IDRnD/VoxTube#6]
Hello 
I am trying to download VoxTube. While downloading I am getting following error message for few samples, 

ERROR: [youtube] 96j3MpaOVBQ: This video is private. If the owner of this video has granted you access, please sign in.      | 12/15 [00:01<00:00,  7.36it/s]

Do you have audio files only dataset ?

**Comment by qsq1017312432** [comment]
Hi, I also ran into this issue, how can I fix it ?

**Comment by wangth2001** [comment]
I'm also getting this problem, can you please package the dataset and upload it ?

**Comment by vanIvan** [comment]
Thanks for noting this out, we are looking for a ways to solve this. In a meantime the only way to to skip this videos.

**Comment by greatjh** [comment]
@vanIvan 

Thank you so much for sharing this very impressive research results.

In the paper you proposed, the generalization performance of the speaker recognition model was improved with VoxTube DB.

I would like to download VoxTube DB and see if the model generalization performance improves.

However, many videos have been deleted and are not downloading properly.

Can I get VoxTube DB for research purposes?

To reproduce performance results, if there is a way to download VoxTube DB, please share the link.

Thanks.

**Comment by vanIvan** [comment]
Hello everyone! Finally full dataset is released in [hugginface](https://huggingface.co/datasets/voice-is-cool/voxtube), closing the issue

**Comment by vanIvan** [comment]
Hello everyone! Finally full dataset is released in [hugginface](https://huggingface.co/datasets/voice-is-cool/voxtube), closing the issue
