### ISSUE TITLE
Some videos have no segments

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [IDRnD/VoxTube#7]
Hello,

I just realized that some videos listed in the json files are associated with an empty array of segments.

One example is `"SiPpOz-PA7Q": []` in `resources/meta/UC9W7ziDxYZNwWqFexyiIHBg.json` but I have found 474 of those.

**Comment by vanIvan** [comment]
Hello everyone! Sorry for long response, some parts of meta might have errors. Finally full dataset is released in [hugginface](https://huggingface.co/datasets/voice-is-cool/voxtube), closing the issue
